/**
 * HTML-in-Canvas Presets — all animations use onFrame(time) for SVG foreignObject compatibility.
 * CSS @keyframes do NOT work in SVG foreignObject snapshots.
 */

export const PRESETS = {
    'google-clean': {
        name: 'Google Clean', cat: 'motion', dur: 5,
        html: '<div class="gc"><div class="logo"><span class="cb" id="l1">G</span><span class="cr" id="l2">o</span><span class="cy" id="l3">o</span><span class="cb" id="l4">g</span><span class="cg" id="l5">l</span><span class="cr" id="l6">e</span></div><div class="sub" id="sub">Animation Engine</div></div>',
        css: '.gc{width:100%;height:100%;background:#fff;display:flex;flex-direction:column;align-items:center;justify-content:center;font-family:Arial,sans-serif}.logo{font-size:110px;font-weight:bold;letter-spacing:-4px}.cb{color:#4285F4}.cr{color:#EA4335}.cy{color:#FBBC05}.cg{color:#34A853}.sub{font-size:26px;color:#5F6368;margin-top:15px;font-weight:300;letter-spacing:2px}',
        js: 'function onFrame(t){for(var i=1;i<=6;i++){var el=document.getElementById("l"+i);if(el){el.style.display="inline-block";el.style.transform="translateY("+Math.sin((t-i*150)/250)*20+"px)"}}var s=document.getElementById("sub");if(s)s.style.opacity=Math.abs(Math.cos(t/1000))}'
    },
    'gradient-hero': {
        name: 'Gradient Hero', cat: 'premium', dur: 5,
        html: '<div class="mw"><div class="blob b1"></div><div class="blob b2"></div><div class="blob b3"></div><div class="blob b4"></div><div class="ct"><h1>Aura Pro</h1><p>Premium Mesh Gradients</p></div></div>',
        css: '.mw{position:relative;width:100%;height:100%;background:#000;overflow:hidden;display:flex;align-items:center;justify-content:center;font-family:system-ui,sans-serif}.blob{position:absolute;border-radius:50%;filter:blur(80px);opacity:.8;mix-blend-mode:screen}.b1{width:400px;height:400px;background:#ff0080;top:-100px;left:-100px}.b2{width:500px;height:500px;background:#7928ca;bottom:-200px;right:-100px}.b3{width:450px;height:450px;background:#0070f3;bottom:-100px;left:10%}.b4{width:350px;height:350px;background:#ff4d4d;top:10%;right:20%}.ct{position:relative;z-index:10;text-align:center;color:white;background:rgba(255,255,255,.05);padding:50px 70px;border-radius:40px;border:1px solid rgba(255,255,255,.15);backdrop-filter:blur(20px);-webkit-backdrop-filter:blur(20px);box-shadow:0 30px 60px rgba(0,0,0,.4)}h1{font-size:72px;font-weight:700;margin:0;letter-spacing:-2px}p{font-size:20px;font-weight:300;margin:15px 0 0;color:rgba(255,255,255,.8)}',
        js: 'function onFrame(t){var b1=document.querySelector(".b1"),b2=document.querySelector(".b2"),b3=document.querySelector(".b3"),b4=document.querySelector(".b4");if(b1)b1.style.transform="translate("+Math.sin(t/2000)*100+"px,"+Math.cos(t/1500)*100+"px)scale("+(1+Math.sin(t/1000)*.2)+")";if(b2)b2.style.transform="translate("+Math.cos(t/1800)*120+"px,"+Math.sin(t/2200)*80+"px)scale("+(1+Math.cos(t/1200)*.2)+")";if(b3)b3.style.transform="translate("+Math.sin(t/2500)*-90+"px,"+Math.cos(t/1900)*110+"px)";if(b4)b4.style.transform="translate("+Math.cos(t/1700)*150+"px,"+Math.sin(t/2100)*-100+"px)"}'
    },
    'brutal': {
        name: 'Neo-Brutal', cat: 'motion', dur: 5,
        html: '<div class="bw"><div class="bc" id="bcard"><h1>NEO<br>BRUTAL</h1><p>HTML in Canvas</p><svg class="shape s1" viewBox="0 0 100 100"><rect x="10" y="10" width="80" height="80" fill="#FF5E5B" stroke="#000" stroke-width="5" rx="4"/></svg><svg class="shape s2" viewBox="0 0 100 100"><circle cx="50" cy="50" r="40" fill="#00CECB" stroke="#000" stroke-width="5"/></svg><svg class="shape s3" viewBox="0 0 100 100"><polygon points="50,8 95,90 5,90" fill="#FFD93D" stroke="#000" stroke-width="5"/></svg><svg class="shape s4" viewBox="0 0 100 100"><rect x="20" y="20" width="60" height="60" fill="#C084FC" stroke="#000" stroke-width="5" rx="30"/></svg></div></div>',
        css: '.bw{width:100%;height:100%;background:#FFED66;display:flex;align-items:center;justify-content:center;font-family:"Courier New",monospace;overflow:hidden}.bc{background:white;border:6px solid black;box-shadow:20px 20px 0 black;padding:50px;position:relative;width:460px}h1{font-size:80px;margin:0;line-height:.9;text-transform:uppercase;letter-spacing:-3px}p{font-size:30px;font-weight:bold;margin-top:16px;background:#000;color:#fff;display:inline-block;padding:5px 14px}.shape{position:absolute;width:100px;height:100px}.s1{top:-40px;right:-40px}.s2{bottom:-30px;right:50px}.s3{top:50%;left:-45px;margin-top:-30px}.s4{bottom:-35px;left:60px}',
        js: 'function onFrame(t){var c=document.getElementById("bcard"),s1=document.querySelector(".s1"),s2=document.querySelector(".s2"),s3=document.querySelector(".s3"),s4=document.querySelector(".s4");if(c)c.style.transform="translate("+Math.cos(t/600)*8+"px,"+Math.sin(t/500)*10+"px)";if(s1)s1.style.transform="rotate("+t/12+"deg)";if(s2)s2.style.transform="scale("+(1+Math.sin(t/250)*.2)+")";if(s3)s3.style.transform="rotate("+(-t/18)+"deg) scale("+(1+Math.cos(t/350)*.15)+")";if(s4)s4.style.transform="translateY("+Math.sin(t/400)*12+"px) rotate("+t/10+"deg)"}'
    },
    'ios-glass': {
        name: 'iOS Glass', cat: 'premium', dur: 5,
        html: '<div class="ib"><div class="bu b1"></div><div class="bu b2"></div><div class="gc2"><div class="ci">&#127822;</div><h2>iOS Glass</h2><p>Smooth blurs in Canvas</p><div class="pb"><div class="pf" id="fill"></div></div></div></div>',
        css: '.ib{width:100%;height:100%;background:#f2f2f7;overflow:hidden;display:flex;align-items:center;justify-content:center;font-family:system-ui,-apple-system,sans-serif;position:relative}.bu{position:absolute;border-radius:50%;filter:blur(40px)}.b1{width:300px;height:300px;background:#ff3b30;top:10%;left:20%}.b2{width:400px;height:400px;background:#007aff;bottom:10%;right:15%}.gc2{width:400px;background:rgba(255,255,255,.4);backdrop-filter:blur(40px);-webkit-backdrop-filter:blur(40px);border:1px solid rgba(255,255,255,.6);border-radius:32px;padding:40px;box-shadow:0 20px 40px rgba(0,0,0,.1);z-index:10}.ci{font-size:48px;margin-bottom:20px}h2{margin:0 0 10px;font-size:28px;color:#1c1c1e}p{margin:0 0 30px;color:#3a3a3c}.pb{height:8px;background:rgba(0,0,0,.1);border-radius:4px;overflow:hidden}.pf{width:0;height:100%;background:#007aff;border-radius:4px}',
        js: 'function onFrame(t){var f=document.getElementById("fill"),b1=document.querySelector(".b1"),b2=document.querySelector(".b2");if(f)f.style.width=((Math.sin(t/1000)+1)/2*100)+"%";if(b1)b1.style.transform="translate("+Math.sin(t/1500)*50+"px,"+Math.cos(t/1200)*50+"px)";if(b2)b2.style.transform="translate("+Math.cos(t/1300)*-60+"px,"+Math.sin(t/1600)*-60+"px)"}'
    },
    'data-chart': {
        name: 'Data Chart', cat: 'data', dur: 5,
        html: '<div class="vx"><div class="ey">THE NUMBERS</div><h1>Where the world\'s electricity<br>actually comes from</h1><div class="ch"><div class="rw"><div class="lb">Coal</div><div class="tk"><div class="br" style="background:#2b2b2b" data-v="35"><span class="vl">0%</span></div></div></div><div class="rw"><div class="lb">Nat. Gas</div><div class="tk"><div class="br" style="background:#6b6b6b" data-v="23"><span class="vl">0%</span></div></div></div><div class="rw"><div class="lb">Hydro</div><div class="tk"><div class="br" style="background:#1f7a8c" data-v="14"><span class="vl">0%</span></div></div></div><div class="rw"><div class="lb">Nuclear</div><div class="tk"><div class="br" style="background:#5551ff" data-v="9"><span class="vl">0%</span></div></div></div><div class="rw"><div class="lb">Wind</div><div class="tk"><div class="br" style="background:#2ecc71" data-v="8"><span class="vl">0%</span></div></div></div><div class="rw"><div class="lb">Solar</div><div class="tk"><div class="br" style="background:#f1c40f" data-v="6"><span class="vl">0%</span></div></div></div><div class="rw"><div class="lb">Other</div><div class="tk"><div class="br" style="background:#b0b0b0" data-v="5"><span class="vl">0%</span></div></div></div></div></div>',
        css: '.vx{width:100%;height:100%;background:#fff;font-family:system-ui,Helvetica,sans-serif;padding:40px 50px;box-sizing:border-box;display:flex;flex-direction:column}.ey{font-weight:800;letter-spacing:2px;font-size:12px;color:#FF3B30;margin-bottom:6px}h1{font-size:27px;line-height:1.15;margin:0 0 18px;font-weight:800}.ch{display:flex;flex-direction:column;gap:10px;flex:1}.rw{display:flex;align-items:center;gap:10px}.lb{width:90px;font-size:12.5px;font-weight:700;text-align:right}.tk{flex:1;background:#f0f0f0;border-radius:3px;height:24px;overflow:hidden}.br{height:100%;width:0;border-radius:3px;display:flex;align-items:center;justify-content:flex-end;padding-right:8px;transition:none}.vl{font-size:11.5px;font-weight:700;color:#fff}',
        js: 'function onFrame(t){var ease=1-Math.pow(1-Math.min(t/2000,1),3);var bars=document.querySelectorAll(".br");for(var i=0;i<bars.length;i++){var v=parseInt(bars[i].getAttribute("data-v"))||0;var p=Math.max(0,Math.min((ease-i*.08)/(1-i*.08),1));bars[i].style.width=(v*2.6*p)+"%";var val=bars[i].querySelector(".vl");if(val)val.textContent=Math.round(v*p)+"%"}}'
    },
    'stagger': {
        name: 'Stagger Grid', cat: 'ui', dur: 5,
        html: '<div class="sw"><div class="sh">FEATURED COLLECTIONS</div><div class="sg"><div class="sc" id="sc0"><div class="ib2"><img src="https://images.unsplash.com/photo-1486325212027-8081e485255e?w=400&h=300&fit=crop&q=80"/></div><span>Architecture</span></div><div class="sc" id="sc1"><div class="ib2"><img src="https://images.unsplash.com/photo-1557682250-33bd709cbe85?w=400&h=300&fit=crop&q=80"/></div><span>Gradients</span></div><div class="sc" id="sc2"><div class="ib2"><img src="https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400&h=300&fit=crop&q=80"/></div><span>Coastal</span></div></div></div>',
        css: '.sw{width:100%;height:100%;background:#090d16;font-family:system-ui,sans-serif;padding:60px;box-sizing:border-box;display:flex;flex-direction:column;justify-content:center}.sh{color:#94a3b8;font-size:14px;font-weight:700;letter-spacing:4px;margin-bottom:25px}.sg{display:flex;gap:24px;width:100%}.sc{flex:1;background:#1e293b;border-radius:16px;overflow:hidden;border:1px solid rgba(255,255,255,.1)}.ib2{width:100%;height:260px;overflow:hidden;background:#334155}.ib2 img{width:100%;height:100%;object-fit:cover}span{display:block;padding:20px;color:#fff;font-size:18px;font-weight:600}',
        js: 'function onFrame(t){for(var i=0;i<3;i++){var el=document.getElementById("sc"+i);if(el){var delay=300+i*200,p=Math.max(0,Math.min((t-delay)/800,1)),e=p===1?1:1-Math.pow(2,-10*p);el.style.opacity=e;el.style.transform="translateY("+((1-e)*50)+"px)"}}}'
    },
    'fireship': {
        name: 'Fireship Terminal', cat: 'code', dur: 4,
        html: '<div class="fs"><span class="badge">100 SECONDS</span><h1 class="gt">Learn any framework FAST</h1><div class="tm"><div class="td"><span></span><span></span><span></span></div><div class="tl"><span class="pr">$</span> <span id="cmd"></span><span class="cu">|</span></div></div></div>',
        css: '.fs{width:100%;height:100%;background:#0a0a0c;display:flex;flex-direction:column;align-items:center;justify-content:center;font-family:system-ui,sans-serif;overflow:hidden;gap:18px}.badge{font-family:monospace;font-size:11px;font-weight:700;color:#0a0a0c;background:#f5d90a;padding:4px 10px;border-radius:4px;letter-spacing:1px}.gt{font-size:40px;font-weight:700;margin:0;text-align:center;max-width:460px;background:linear-gradient(90deg,#ff5ec4,#7873f5,#35e2c4);-webkit-background-clip:text;background-clip:text;color:transparent}.tm{width:380px;background:#131417;border:1px solid #26272c;border-radius:8px;overflow:hidden}.td{display:flex;gap:6px;padding:8px 10px;background:#1b1c20}.td span{width:9px;height:9px;border-radius:50%;background:#3a3b41}.td span:first-child{background:#ff5f57}.td span:nth-child(2){background:#febc2e}.td span:nth-child(3){background:#28c840}.tl{padding:12px 14px;font-family:monospace;font-size:13px;color:#d6d6da}.pr{color:#35e2c4}.cu{color:#d6d6da}',
        js: 'var _ft="npx create-app@latest --fast";function onFrame(t){var el=document.getElementById("cmd");if(el){var n=Math.min(_ft.length,Math.max(0,Math.floor((t-1300)/38)));el.textContent=_ft.slice(0,n)}}'
    },
    'material-you': {
        name: 'Material You', cat: 'premium', dur: 5,
        html: '<div class="ms"><div class="blob blob1"></div><div class="blob blob2"></div><div class="blob blob3"></div><div class="mc" id="mcard"><span class="chip" id="mchip">New</span><h1 class="mt" id="mtitle">Designed to feel alive.</h1><p class="mu" id="msub">Material You adapts to you.</p><div class="m-dots"><span class="mdot" style="background:#4285F4"></span><span class="mdot" style="background:#34A853"></span><span class="mdot" style="background:#FBBC05"></span><span class="mdot" style="background:#EA4335"></span></div></div></div>',
        css: '.ms{width:100%;height:100%;background:#101418;display:flex;align-items:center;justify-content:center;overflow:hidden;position:relative;font-family:system-ui,Arial,sans-serif}.blob{position:absolute;border-radius:50%;filter:blur(40px);opacity:.55}.blob1{width:280px;height:280px;background:radial-gradient(circle,#4285F4,#8ab4f8);top:-80px;left:-80px}.blob2{width:250px;height:250px;background:radial-gradient(circle,#34A853,#FBBC05);bottom:-80px;right:-60px}.blob3{width:200px;height:200px;background:radial-gradient(circle,#EA4335,#ff6ec4);top:50%;left:60%;margin-top:-100px}.mc{position:relative;z-index:2;background:rgba(255,255,255,.06);backdrop-filter:blur(18px);border:1px solid rgba(255,255,255,.12);border-radius:28px;padding:34px 38px;max-width:360px}.chip{display:inline-block;background:linear-gradient(90deg,#4285F4,#34A853);color:#fff;font-size:11px;font-weight:700;padding:4px 12px;border-radius:20px;letter-spacing:.5px;margin-bottom:14px}.mt{font-size:30px;font-weight:600;color:#e8eaed;margin:0 0 10px;line-height:1.25}.mu{color:#9aa0a6;font-size:15px;margin:0}.m-dots{display:flex;gap:8px;margin-top:20px}.mdot{width:10px;height:10px;border-radius:50%}',
        js: 'function onFrame(t){var b1=document.querySelector(".blob1"),b2=document.querySelector(".blob2"),b3=document.querySelector(".blob3"),card=document.getElementById("mcard"),chip=document.getElementById("mchip"),title=document.getElementById("mtitle"),sub=document.getElementById("msub"),dots=document.querySelectorAll(".mdot");if(b1)b1.style.transform="translate("+Math.sin(t/2500)*60+"px,"+Math.cos(t/2000)*50+"px)scale("+(1+Math.sin(t/1500)*.15)+")";if(b2)b2.style.transform="translate("+Math.cos(t/2200)*-70+"px,"+Math.sin(t/2800)*40+"px)scale("+(1+Math.cos(t/1800)*.15)+")";if(b3)b3.style.transform="translate("+Math.cos(t/3000)*40+"px,"+Math.sin(t/2600)*-30+"px)";var cp=Math.min(1,t/400);if(card)card.style.transform="translateY("+((1-cp)*30)+"px) scale("+(0.9+cp*.1)+")";if(chip)chip.style.opacity=Math.min(1,Math.max(0,(t-200)/300));if(title){var tp=Math.min(1,Math.max(0,(t-400)/400));title.style.opacity=tp;title.style.transform="translateY("+((1-tp)*12)+"px)"}if(sub)sub.style.opacity=Math.min(1,Math.max(0,(t-700)/400));for(var i=0;i<dots.length;i++)dots[i].style.transform="scale("+(1+Math.sin(t/800+i*1.5)*.4)+")"}'
    },
    'ios-gradient': {
        name: 'iOS Gradient', cat: 'premium', dur: 5,
        html: '<div class="igs"><div class="imesh"></div><div class="orb o1"></div><div class="orb o2"></div><div class="orb o3"></div><div class="ic" id="icard"><h1 class="ih" id="ititle">Beautifully simple.</h1><p class="is2" id="isub">Designed for everyone.</p><div class="iline" id="iline"></div></div></div>',
        css: '.igs{width:100%;height:100%;position:relative;display:flex;align-items:center;justify-content:center;font-family:-apple-system,system-ui,Arial,sans-serif;overflow:hidden}.imesh{position:absolute;inset:0;background:radial-gradient(circle at 20% 30%,#ff6ec4,transparent 55%),radial-gradient(circle at 80% 20%,#7873f5,transparent 55%),radial-gradient(circle at 50% 85%,#4adede,transparent 55%),#05060a;filter:saturate(1.3)}.ic{position:relative;z-index:2;text-align:center}.ih{font-size:50px;font-weight:700;letter-spacing:-1.5px;margin:0;color:#fff}.is2{margin-top:14px;font-size:19px;color:rgba(255,255,255,.75)}.orb{position:absolute;border-radius:50%;filter:blur(60px);opacity:.5;mix-blend-mode:screen}.o1{width:180px;height:180px;background:#ff6ec4;top:20%;left:15%}.o2{width:150px;height:150px;background:#7873f5;bottom:20%;right:20%}.o3{width:120px;height:120px;background:#4adede;top:60%;left:55%}.iline{width:0;height:3px;margin:20px auto 0;border-radius:2px;background:linear-gradient(90deg,#ff6ec4,#7873f5,#4adede)}',
        js: 'function onFrame(t){var m=document.querySelector(".imesh"),o1=document.querySelector(".o1"),o2=document.querySelector(".o2"),o3=document.querySelector(".o3"),title=document.getElementById("ititle"),sub=document.getElementById("isub"),line=document.getElementById("iline");if(m)m.style.filter="saturate("+(1.3+Math.sin(t/3000)*.3)+") hue-rotate("+(Math.sin(t/5000)*20)+"deg)";if(o1)o1.style.transform="translate("+Math.sin(t/2000)*80+"px,"+Math.cos(t/1800)*60+"px)scale("+(1+Math.sin(t/1200)*.2)+")";if(o2)o2.style.transform="translate("+Math.cos(t/2500)*-60+"px,"+Math.sin(t/2200)*70+"px)";if(o3)o3.style.transform="translate("+Math.sin(t/1600)*50+"px,"+Math.cos(t/3000)*-40+"px)scale("+(1+Math.cos(t/1000)*.25)+")";var tp=Math.min(1,Math.max(0,(t-200)/500));if(title){title.style.opacity=tp;title.style.transform="translateY("+((1-tp)*20)+"px)"}if(sub)sub.style.opacity=Math.min(1,Math.max(0,(t-600)/400));var lp=Math.min(1,Math.max(0,(t-800)/600));if(line)line.style.width=(lp*180)+"px"}'
    },
    'vox-title': {
        name: 'Vox Title', cat: 'text', dur: 3,
        html: '<div class="vs"><span class="vk" id="vkicker">THE EXPLAINER</span><div class="vr" id="vrule"></div><h1 class="vt" id="vtitle">Why this actually matters right now</h1><span class="vg" id="vtag">4 min read</span></div>',
        css: '.vs{width:100%;height:100%;background:#111;display:flex;flex-direction:column;align-items:center;justify-content:center;font-family:system-ui,Arial,sans-serif;overflow:hidden;padding:40px 50px;text-align:center}.vk{display:inline-block;font-size:14px;font-weight:700;letter-spacing:3px;color:#FF3B30;margin-bottom:12px}.vr{height:6px;width:0;background:#FF3B30;margin-bottom:18px;border-radius:3px}.vt{font-weight:900;font-size:52px;line-height:1;color:#f5f5f5;text-transform:uppercase;margin:0 0 20px;letter-spacing:-.5px}.vg{display:inline-block;font-size:14px;font-weight:600;color:#9a9a9a}',
        js: 'function onFrame(t){var k=document.getElementById("vkicker"),r=document.getElementById("vrule"),ti=document.getElementById("vtitle"),g=document.getElementById("vtag");if(k)k.style.opacity=Math.min(1,t/200);if(r)r.style.width=Math.min(120,Math.max(0,(t-300)/600*120))+"px";if(ti){var p=Math.max(0,Math.min((t-500)/500,1));ti.style.opacity=p;ti.style.transform="translateY("+((1-p)*16)+"px)"}if(g)g.style.opacity=Math.min(1,Math.max(0,(t-1000)/400))}'
    },
    'reveal': {
        name: 'Text Reveal', cat: 'text', dur: 3,
        html: '<div class="rw2"><h1 class="rh" id="headline">Make it clear.</h1><div class="rs" id="sweep"></div><p class="rp" id="rsub">Simple, fast, helpful.</p></div>',
        css: '.rw2{width:100%;height:100%;background:#fff;display:flex;flex-direction:column;align-items:center;justify-content:center;font-family:system-ui,sans-serif;text-align:center;padding:40px}.rh{font-size:60px;font-weight:600;margin:0;color:#1f1f1f;letter-spacing:-2px;line-height:1.1}.rh .ch{display:inline-block;opacity:0;transform:translateY(24px)}.rs{height:5px;width:0;margin:24px auto;border-radius:3px;background:linear-gradient(90deg,#4285F4,#EA4335,#FBBC05,#34A853)}.rp{margin-top:0;font-size:20px;color:#5f6368;opacity:0}',
        js: 'var _rt="Make it clear.";function onFrame(t){var ch=document.querySelectorAll(".ch");if(!ch.length){var h=document.getElementById("headline");if(h){h.innerHTML="";for(var i=0;i<_rt.length;i++){var sp=document.createElement("span");sp.className="ch";sp.textContent=_rt[i]===" "?"\u00a0":_rt[i];h.appendChild(sp)}ch=document.querySelectorAll(".ch")}}for(var i=0;i<ch.length;i++){var d=100+i*40,p=Math.max(0,Math.min((t-d)/400,1)),e=p===1?1:1-Math.pow(2,-10*p);ch[i].style.opacity=e;ch[i].style.transform="translateY("+((1-e)*24)+"px)"}var sw=document.getElementById("sweep");if(sw)sw.style.width=Math.min(280,Math.max(0,(t-900)/800*280))+"px";var sub=document.getElementById("rsub");if(sub)sub.style.opacity=Math.max(0,Math.min((t-1400)/500,1))}'
    },
    'gsearch': {
        name: 'Google Search', cat: 'ui', dur: 4,
        html: '<div class="gw"><div class="gb"><span class="gd" style="background:#4285F4"></span><span class="gd" style="background:#EA4335"></span><span class="gd" style="background:#FBBC05"></span><span class="gd" style="background:#34A853"></span><span class="gq" id="gq"></span><span class="gc3" id="gcaret">|</span></div><div class="ga" id="gans"><h1>Search, simplified.</h1><p>Instant answers, right where you need them.</p></div></div>',
        css: '.gw{width:100%;height:100%;background:#fff;display:flex;align-items:center;justify-content:center;font-family:system-ui,Arial,sans-serif;flex-direction:column;gap:24px}.gb{display:flex;align-items:center;gap:10px;background:#fff;border:1px solid #dfe1e5;border-radius:24px;padding:12px 20px;box-shadow:0 1px 6px rgba(32,33,36,.18)}.gd{width:9px;height:9px;border-radius:50%;flex-shrink:0}.gq{font-family:monospace;font-size:15px;color:#202124;white-space:nowrap}.gc3{color:#4285F4;font-weight:700}.ga{padding-left:6px;opacity:0;transform:translateY(10px)}.ga h1{font-size:24px;font-weight:500;color:#202124;margin:0 0 6px}.ga p{font-size:15px;color:#5f6368;margin:0}',
        js: 'var _gt="how does it feel to search less";function onFrame(t){var el=document.getElementById("gq"),ans=document.getElementById("gans"),c=document.getElementById("gcaret");if(el){var n=Math.min(_gt.length,Math.max(0,Math.floor((t-300)/45)));el.textContent=_gt.slice(0,n)}if(ans){var ap=Math.max(0,Math.min((t-2200)/600,1));ans.style.opacity=ap;ans.style.transform="translateY("+((1-ap)*10)+"px)"}if(c)c.style.opacity=Math.abs(Math.sin(t/500))}'
    }
};

export default PRESETS;
